<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
        <tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Use of undefined constant Id - assumed 'Id' in D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WebServices\WS_Library.php on line <i>49</i></th></tr>
        <tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
        <tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
        <tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>253928</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WSController.php' bgcolor='#eeeeec'>..\WSController.php<b>:</b>0</td></tr>
        <tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0023</td><td bgcolor='#eeeeec' align='right'>301992</td><td bgcolor='#eeeeec'>WS_Library->doPost(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WSController.php' bgcolor='#eeeeec'>..\WSController.php<b>:</b>30</td></tr>
        <tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0023</td><td bgcolor='#eeeeec' align='right'>302080</td><td bgcolor='#eeeeec'>WS_Library->GetLibraryClient(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WebServices\WS_Library.php' bgcolor='#eeeeec'>..\WS_Library.php<b>:</b>34</td></tr>
    </table></font>
<br />
<font size='1'><table class='xdebug-error xe-catchable-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
        <tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Catchable fatal error: Object of class stdClass could not be converted to string in D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WebServices\WS_Library.php on line <i>49</i></th></tr>
        <tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
        <tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
        <tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>253928</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WSController.php' bgcolor='#eeeeec'>..\WSController.php<b>:</b>0</td></tr>
        <tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0023</td><td bgcolor='#eeeeec' align='right'>301992</td><td bgcolor='#eeeeec'>WS_Library->doPost(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WSController.php' bgcolor='#eeeeec'>..\WSController.php<b>:</b>30</td></tr>
        <tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0023</td><td bgcolor='#eeeeec' align='right'>302080</td><td bgcolor='#eeeeec'>WS_Library->GetLibraryClient(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WebServices\WS_Library.php' bgcolor='#eeeeec'>..\WS_Library.php<b>:</b>34</td></tr>
    </table></font>