<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
        <tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Call to a member function setFetchMode() on a non-object in D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\Database\db_connect.php on line <i>40</i></th></tr>
        <tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
        <tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
        <tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>252672</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WSController.php' bgcolor='#eeeeec'>..\WSController.php<b>:</b>0</td></tr>
        <tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0020</td><td bgcolor='#eeeeec' align='right'>310976</td><td bgcolor='#eeeeec'>WS_User->doPost(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WSController.php' bgcolor='#eeeeec'>..\WSController.php<b>:</b>30</td></tr>
        <tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0020</td><td bgcolor='#eeeeec' align='right'>311104</td><td bgcolor='#eeeeec'>WS_User->ModifUser(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WebServices\WS_User.php' bgcolor='#eeeeec'>..\WS_User.php<b>:</b>42</td></tr>
        <tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0021</td><td bgcolor='#eeeeec' align='right'>313744</td><td bgcolor='#eeeeec'>MySQL::Execute(  )</td><td title='D:\Logiciel Travail\wamp\www\BibliothequeAudioV2\php\WebServices\WS_User.php' bgcolor='#eeeeec'>..\WS_User.php<b>:</b>98</td></tr>
    </table></font>